server:
  port: 8054

spring:
  application:
    name: GateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authenticationmicroservice
          uri: lb://authenticationmicroservice
          predicates:
            - Path=/v1/**
        - id: nodeapp
          uri: http://nodeapp:3000
          predicates:
            - Path=/todo/**
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka