version: "3.8"
services:
  ui:
    build: ./MonoRepoWithJS/ui
    image: ui
    container_name: ui
    ports:
      - "8080:80"

  node:
    container_name: nodeapp
    build: ./MonoRepoWithJS/api
    ports:
      - "3000:3000"
    hostname: nodeapp
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    image: nodeapp
    depends_on:
      - eureka
      - mongo
    command: npm start
    # node:
    #   container_name: node-service
    #   image: "node-service"
    #   build: ./node-service
    #   ports:
    #     - "3000:5000"
    #   hostname: node-service
    #   environment:
    #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=eureka-server
    #   depends_on:
    #     - "Eureka"
    #     - "Mongo"
    #   command: "node ./index.js"
  auth:
    container_name: authenticationmicroservice
    build: ./MonoRepoWithSpring/authenticationmicroservice
    ports:
      - "8081:8081"
    hostname: authenticationmicroservice
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_HOST=eureka
      - MYSQL_HOST=mysql
    image: authenticationmicroservice
    depends_on:
      - eureka
  gateway:
    container_name: GateWay
    build: ./MonoRepoWithSpring/GateWay
    ports:
      - "8054:8054"
    hostname: GateWay
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - eureka
  # node:
  #   container_name: node-service
  #   image: "node-service"
  #   build: ./node-service
  #   ports:
  #     - "3000:5000"
  #   hostname: node-service
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=eureka-server
  #   depends_on:
  #     - "Eureka"
  #     - "Mongo"
  #   command: "node ./index.js"
  eureka:
    container_name: eurekaserver
    build: ./MonoRepoWithSpring/eurekaserver
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  configserver:
    container_name: configserver
    build: ./MonoRepoWithSpring/configserver
    ports:
      - "8889:8889"
    hostname: configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  mongo:
    container_name: mongo
    image: "mongo:5-focal"
    ports:
      - "27017:27017"
    hostname: mongodb
    depends_on:
      - "eureka"
    volumes:
      - mongodata:/data/db
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=userdb
    ports:
      - "3306:3306"
volumes:
  mongodata:
